title: Path to Spectral
description: Research, AI, and Mathematics
url: "https://pathtoscience.github.io"
baseurl: "/pathtospectral.github.io"
theme: null

markdown: kramdown
social:
  scholar: "https://scholar.google.com/citations?user=rW2NUVcAAAAJ&hl=fr"
  linkedin: "https://www.linkedin.com/in/mamadou-path%C3%A9-ly-phd-ba3791174/"
  x: "https://x.com/ly1_path"

navigation:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/
