title: Path to Spectral
description: Research, AI, and Mathematics
url: "https://pathtoscience.github.io"
baseurl: "/pathtospectral.github.io"
theme: null

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Publications
    url: /publications/
  - title: Software
    url: /software/
  - title: Blog
    url: /blog/
